---
# create a new VM from a template

- name: VM from template
  hosts: localhost
  gather_facts: false
  connection: local
  vars:
    vcenter_hostname: 192.168.1.10
    vcenter_user: administrator@vsphere.local
    vcenter_pass: Keep-2-urself
    esxhost: 192.168.1.12
    datastore: Synology1
    vmtemplate: Ubuntu20
    name: Ubuntu_sandbox
    notes: Ansible VM Provisioning
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: False
        esxi_hostname: "{{ esxhost }}"
        datacenter: BRODWAY_NJ
        folder: /BRODWAY_NJ/vm
        name: "{{ name }}"
        template: "{{ vmtemplate }}"
        disk:
          - size_gb: "{{ disk_size | default(30) }}"
            type: thin
            datastore: "{{ datastore }}"
        networks:
        - name: VM Network
          type: dhcp
        hardware:
          memory_mb: "{{ vm_memory | default(1024) }}"
        wait_for_ip_address: True
        state: present
      register: newvm

    - name: IP address info
      debug:
        msg: "{{ newvm.instance.ipv4 }} {{ name }}"

