---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.168.1.10
      username: administrator@vsphere.local
      password: Keep-2-urself
      validate_certs: False
      name: testAnsImage
      template: UbuntuServer19
      datacenter: BRODWAY_NJ
      folder: /BRODWAY_NJ/vm
      state: poweredon
      wait_for_ip_address: yes
